dbConfigs:
  Usercenter:
    fileName: "./CloudSilk.s3db"
    dbType: "sqlite"
  Curd:
    fileName: "./CloudSilk.s3db"
    dbType: "sqlite"
  CloudSilk:
    connectionStr: "root:password@(127.0.0.1:3306)/mom?charset=utf8mb4&parseTime=True&loc=Local"
    dbType: "mysql"
  all:
    fileName: "./CloudSilk.s3db"
    dbType: "sqlite"
debug: false
token:
  key: "CloudSilk"
  redisAddr: ""
  redisUserName: ""
  redisPwd: ""
  expired: 86400
superAdminRoleID: "1"
platformTenantID: "2012ae3c-6f5f-4d10-9a59-ca0dd7c058a5"
defaultRoleID: 7434dc3b-fabc-4ada-9332-6ddf30e0356a
defaultPwd: CloudSilk
miniApp:
  - id: ""
    name: ""
    secret: ""
    tenantID: ""